# Generated by Django 4.0.4 on 2022-06-03 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
